name: Power Platform CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Install Power Platform CLI
      run: dotnet tool install --global Microsoft.PowerApps.CLI.Tool

    - name: Add .NET Tools to PATH
      run: echo "::add-path::%USERPROFILE%\.dotnet\tools"

    - name: Verify Power Platform CLI Installation
      run: pac --version

    - name: Export Solution
      run: |
        pac solution export --path ./solutions --name GitHubActionDevo --environment https://orgca0b6436.crm11.dynamics.com/
      env:
        AZURE_CLIENT_ID: ${{ secrets.POWER_PLATFORM_SPN }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Unpack Solution
      run: |
        pac solution unpack --zipfile ./solutions/GitHubActionDevo.zip --folder ./solutions/unpacked
