name: Power Platform CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
      
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: 'https://orgca0b6436.crm11.dynamics.com'
        user-name: 'Yasir@numrexpk.onmicrosoft.com'
        password-secret: ${{ secrets.PASSWORD }}
        solution-name: GitHubActionDevo
        solution-output-file: 'GitHubActionDevo.zip'
        working-directory: 'out'

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: 'out/GitHubActionDevo.zip'
        solution-folder: 'out/solutions/solution_one'
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v1
      with:
        environment-url: 'https://sjp-hr.crm11.dynamics.com'
        user-name: 'Yasir@numrexpk.onmicrosoft.com'
        password-secret: ${{ secrets.PASSWORD }}

    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: 'out/solutions/solution_one'
        solution-target-folder: 'src/solutions/solution1'
        token: ${{ secrets.GITHUB_TOKEN }}
